#!/bin/bash
git clone --branch 0.0.3 git@github.com:AlephVault/unity-support.git  ../unity-support
git clone --branch 0.0.1 git@github.com:AlephVault/unity-support-generic.git ../unity-support-generic
git clone --branch 0.0.2 git@github.com:AlephVault/unity-boilerplates.git ../unity-boilerplates
git clone --branch 0.0.1 git@github.com:AlephVault/unity-layout.git ../unity-layout
git clone --branch 0.0.2 git@github.com:AlephVault/unity-menu-actions.git ../unity-menu-actions
git clone --branch 0.0.1 git@github.com:AlephVault/unity-soundaround.git ../unity-soundaround
git clone --branch 0.0.4 git@github.com:AlephVault/unity-spriteutils.git ../unity-spriteutils
git clone --branch 0.0.1 git@github.com:AlephVault/unity-textureutils.git ../unity-textureutils
git clone --branch 0.0.2 git@github.com:AlephVault/unity-binary.git ../unity-binary
git clone --branch 0.0.6 git@github.com:AlephVault/unity-meetgard.git ../unity-meetgard
git clone --branch 0.0.5 git@github.com:AlephVault/unity-meetgard-auth.git ../unity-meetgard-auth
git clone --branch 0.0.3 git@github.com:AlephVault/unity-meetgard-scopes.git ../unity-meetgard-scopes
git clone --branch 0.0.2 git@github.com:AlephVault/unity-remotestorage.git ../unity-remotestorage
git clone --branch 0.0.2 git@github.com:AlephVault/unity-backpack.git ../unity-backpack
git clone --branch 0.0.2 git@github.com:AlephVault/unity-gabtab.git ../unity-gabtab
git clone --branch 0.0.8 git@github.com:AlephVault/unity-windrose.git ../unity-windrose
git clone --branch 0.0.4 git@github.com:AlephVault/unity-windrose-biomes.git ../unity-windrose-biomes
git clone --branch 0.0.2 git@github.com:AlephVault/unity-windrose-backpack-plugin.git ../unity-windrose-backpack-plugin
git clone --branch 0.0.2 git@github.com:AlephVault/unity-windrose-gabtab-plugin.git ../unity-windrose-gabtab-plugin
git clone --branch 0.0.4 git@github.com:AlephVault/unity-windrose-spriteutils.git ../unity-windrose-spriteutils
git clone --branch 0.0.3 git@github.com:AlephVault/unity-windrose-neighbourteleports.git ../unity-windrose-neighbourteleports
git clone --branch 0.0.1 git@github.com:AlephVault/unity-windrose-cubeworlds.git ../unity-windrose-cubeworlds
git clone --branch 0.0.5 git@github.com:AlephVault/unity-windrose-refmapchars.git ../unity-windrose-refmapchars
git clone --branch 0.0.1 git@github.com:AlephVault/unity-windrose-lpcbiomes.git ../unity-windrose-lpcbiomes
git clone --branch 0.0.6 git@github.com:AlephVault/unity-netrose.git ../unity-netrose
git clone --branch 0.0.2 git@github.com:AlephVault/unity-netrose-storage.git ../unity-netrose-storage
git clone --branch 0.0.3 git@github.com:AlephVault/unity-netrose-refmapchars.git ../unity-netrose-refmapchars
git clone --branch 0.0.1 git@github.com:AlephVault/unity-ipfs.git ../unity-ipfs
git clone --branch 0.0.1 git@github.com:AlephVault/unity-deeplinks.git ../unity-deeplinks
git clone --branch 0.0.1 git@github.com:AlephVault/unity-evmgames-wallets.git ../unity-evmgames-wallets
git clone --branch 0.0.4 git@github.com:AlephVault/unity-evmgames-auth.git ../unity-evmgames-auth
git clone --branch 0.0.3 git@github.com:AlephVault/unity-evmgames-livecache.git ../unity-evmgames-livecache
git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-localstorage.git ../unity-evmgames-localstorage
git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-contracts.git ../unity-evmgames-contracts
git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-bridge-contract.git ../unity-evmgames-bridge-contract
git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-deeplinks.git ../unity-evmgames-deeplinks

